[cv]
name = "Qianlong Sang"
email = "hacksonsang@gmail.com"
website = "https://codefuturesql.top"
school = "Wuhan University"
# 路径
avatar = ""

[[interests]]
text = "My current research interests focus on leveraging task scheduling and frequency scaling on mobile heterogeneous CPU to meet user performance requirements and achieve power savings. Additionally, I am engaged in some performance profiling work. My future research will shift from traditional application to machine learning tasks."



[[educations]]
school = "Wuhan University"
major = "Computer Science and Technology"
degree = "Ph.D.->M.S."
date = "2022.9 - now"
footnote = "I am considering pursuing a master's degree instead of a Ph.D. for some personal reasons."

[[educations]]
school = "Wuhan University"
major = "Cyber Science and Engineering"
degree = "B.S."
date = "2018.9 - 2022.6"
footnote = ""

[[under_reviews]]
name = "QoE-Aware Power Management Via Scheduling and Governing Co-Optimization on Mobile Devices."
author_list = "Qianlong Sang, Jinqi Yan, Rui Xie, Chuang Hu, Kun Suo, Dazhao Chen"

[[jr_publications]]
name = "Incendio: Priority-based Scheduling for Alleviating Cold Start in Serverless Computing."
where = "IEEE Transactions on Computers"
abbr = "TC"
author_list = "XinQuan Cai, Qianlong Sang, Chuang Hu, Yili Gong, Kun Suo, Xiaobo Zhou"
year = "2024"


[[jr_publications]]
name = "TAPU: A Transmission-Analytics Processing Unit for Accelerating Multifunctions in IoT Gateways."
where = "IEEE Internet of Things Journal"
abbr = "IOTJ"
author_list = "Huanghuang Liang, Qianlong Sang, Chuang Hu, Yili Gong, Dazhao Cheng, Xiaobo Zhou, Yu Wang"
year = "2023"

[[jr_publications]]
name = "An Edge-Side Real-Time Video Analytics System With Dual Computing Resource Control."
where = "IEEE Transactions on Computers"
abbr = "TC"
author_list = "Chuang Hu, Rui Lu, Qianlong Sang, Huanghuang Liang, Dan Wang, Dazhao Cheng, Jin Zhang, Qing Li, Junkun Peng"
year = "2023"

[[jr_publications]]
name = "DNN Surgery: Accelerating DNN Inference on the Edge Through Layer Partitioning."
where = "IEEE Transactions on Cloud Computing"
abbr = "TCC"
author_list = "Huanghuang Liang, Qianlong Sang, Chuang Hu, Dazhao Cheng, Xiaobo Zhou, Dan Wang, Wei Bao, Yu Wang"
year = "2023"


[[h_projects]]
name = "DVFS Energy Consumption Modeling and Algorithm Technology Cooperation."
company = "Huawei Technologies Co., Ltd."
role = "Technology Lead"
date = "2024.04 - 2024.12"
points = ["Responsible for improving the accuracy of load statistics in the system.", "Responsible for enhancing the algorithms for frequency scaling in the system."]
status = "Ongoing"

[[h_projects]]
name = "Thread Identification in the Diverse Rendering Pipelines of Mobile Devices."
company = "OPPO."
role = "Technology Lead"
date = "2024.05 - 2025.04"
points = ["Responsible for analyzing diverse rendering pipeline processes at the upper levels.", "Responsible for instrumenting interfaces that reflect dependency relationships across different layers of the system."]
status = "Ongoing"

[[h_projects]]
name = "Scheduling and DVFS Technology for Mobile Devices Performance and Power Consumption Awareness."
company = "OPPO."
role = "Technology Lead"
date = "2021.12 - 2022.11"
points = ["Responsible for utilizing reinforcement learning algorithms for frequency scaling to make smarter decisions.", "Responsible for achieving performance goals and reducing power consumption through joint scheduling and frequency scaling."]
status = "Finished"


[[projects]]
name = "WHURISCV"
url = "https://github.com/codefuturedalao/oscpu-framework"
date = "2021.07 - 2021.10"
desc = "A five stages riscv64-I CPU for ysyx in 2021"
points = [
    "Responsible for all the work for the CPU."
]

[[projects]]
name = "WHUMIPS"
url = "https://github.com/codefuturedalao/WHUMIPS"
date = "2020.5 - 2020.8"
desc = "A five stages mips CPU with cache for NSCSCC in 2020"
points = [
    "Responsible for all the work for the CPU."
]

[[internships]]
company = "OPPO"
jobtitle = "Research Intern"
date = "2022.2 - 2022.5"
points = ["Performance Analysis ", "Power Optimization"]

[[awards]]
name = "Second-Class Scholarship for Outstanding Students, Wuhan University, 2021"
date = "2021"

[[awards]]
name = "Third Prize, NSCSCC Team Competition, 2020"
date = "2020"

[[teachings]]
name = "Data Structure"
role = "Teaching Assistant"
date = "2023"

[[teachings]]
name = "Operating System"
role = "Teaching Assistant"
date = "2021"

[[teachings]]
name = "YSYX Project of Beijing Institute of Open Source Chip"
role = "Teaching Assistant"
date = "2021"
